# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaults: &defaults
  working_directory: ~/app
  docker:
    - image: node:16-alpine
orbs:
  node: circleci/node@5.1.0
jobs:
  setup_workspace:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - app
  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install Dependencies
          command: yarn
      - persist_to_workspace:
          root: ~/
          paths:
            - app
  unit_test:
    <<: *defaults
    steps:
      - node/test:
          version: "16.17"
workflows:
  test:
    jobs:
      - install_dependencies
      - unit_test:
          requires:
          - install_dependencies
